import type { Metadata } from "next";
import "@/app/globals.css";
import { Analytics } from "@vercel/analytics/react";
import { Providers } from "@/app/providers";
import HeroNavbar from "@/app/components/HeroNavbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <Providers>
          <HeroNavbar />
          {/* <div className="flex justify-center min-h-screen">
            <div className="w-full max-w-4xl"> */}
          {children}
          {/* </div>
          </div> */}
        </Providers>
        <Analytics />
      </body>
    </html>
  );
}
